name: Jekyll site CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker compose up jekyll-build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        target_branch: master
        build_dir: _site
        fqdn: mintobit.com
        jekyll: false
